### PR TITLE
Added Splay tree creation and insertion program.

### PR DESCRIPTION
**Pull request by Braj65**
Added a program for Splay Tree insertion. Let me know your thoughts once you get a chance.

### CODE REVIEW

**Comment by williamfiset** [comment]
Awesome! I'm at a Hackathon today but I will have a look soon!

**Comment by williamfiset** [comment]
Overall the code is very good and easy to follow, well done. I added some tests which are currently failing because something is wrong I'm not sure what. I added a shell script called 'test_splay_tree.sh' which you can use to run TestSplayTest.java in the new tests/ folder.

Question: Does this implementation support multiple keys with the same value? I don't feel like it should but I may be wrong.

Request: Can you also add an isEmpty() method and a size() method so that we can track the number of the elements inside the splay tree.

Optional request: Right now we can insert items into the splay tree and verify their existence within the splay tree, is there a way to remove elements?

**Comment by Braj65** [comment]
I will work on the first request and deliver it in some time. About the optional request, i don't have a clear idea how it can be achieved. I will work on it sometime later.

**Comment by williamfiset** [comment]
I've got a pretty good idea on how to do removals so I can handle that once the insertion algorithm is fixed. The basic idea is to first check if the item is in the splay tree using the contains method, then perform a splay operation to move the node you wanna remove the top, then remove it, and finally merge the two subtrees which are leftover with a join operation. It's a bit of work, but I can probably manage.

**Comment by Braj65** [comment]
Added three separate methods.

**Comment by williamfiset** [comment]
I slightly changed the project structure (the build system in particular). Make such to have a glace at the new README when you have a chance.

**Comment by Braj65** [comment]
I went through it. I will run the tests and update you.

**Comment by Braj65** [comment]
Hi William. The gradle build is failing at  data-structures/Utils/TreePrinter.java Line 75 and 77 because of the unicode chars. I am not able to ignore that file because classes are dependent on it. What do you suggest?

**Comment by williamfiset** [comment]
@Braj65 can you share your error, java version, and OS? Also, make sure you've synced to head when working on a branch i've made that mistakes a few times.

The splaytree class is shaping up pretty good. Can you add tests for duplicate values? Make a judgment call for whether or not this implementation should handle that. In other implementations I have tended to avoid duplicate values because they cause issues.

**Comment by Braj65** [comment]
@williamfiset 
i) My forked branch is in sync and updated to upstream master branch- git fetch upstream, git pull upstream master
ii) I am running gradle build on the master without any of my changes. Below is sample error message-
\Utils\TreePrinter.java:91: error: unmappable character for encoding Cp1252
            System.out.print(j % 2 == 0 ? "┌" : "▒?");
                                                     ^
Utils\TreePrinter.java:75: error: unclosed character literal
              c = (line.get(j) != null) ? '┴' : '┘';
                                          ^
\Utils\TreePrinter.java:77: error: unclosed character literal
              if (j < line.size() && line.get(j) != null) c = '└';
                                                                  ^
Utils\TreePrinter.java:77: error: ';' expected
              if (j < line.size() && line.get(j) != null) c = '└';
I will make the suggested changes to SplayTree.

**Pull request closed without merging**
